### ISSUE TITLE
pkilling Polybar in scripts/hidebars.sh

### ISSUE THREAD

**Issue by maxdevjs** [NerdyPepper/dotfiles#10]
Hi,

going through your config, I wonder if you have a specific need in [scripts/hidebars.sh](https://github.com/NerdyPepper/dotfiles/blob/master/scripts/scripts/hidebars.sh) to `pkill` Polybar in contrast to the option `polybar-msg cmd toggle` or similar.

**Comment by oppiliappan** [comment]
oh i didn't know i could do that. thanks!

fwiw, i don't use polybar anymore.
