### ISSUE TITLE
polybar in herbstluft' without probs?

### ISSUE THREAD

**Issue by pjhalsli** [NerdyPepper/dotfiles#6]
Not an issue at all - more of a question.
I heard you got polybar to work perfectly with hlwm and got curious how you managed to do it?

I will look trough every single word in your files regrding hlwm nd polybar to see if I can figurei t out. For me it's been nothing but failure

**Comment by oppiliappan** [comment]
Could you elaborate why?

Try running polybar in a terminal:

```$ polybar <name of bar>```

If there are any errors, it should show up.
