### ISSUE TITLE
Terminal Colors

### ISSUE THREAD

**Issue by iyzg** [NerdyPepper/dotfiles#8]
Is there a place where I could find the terminal colors you use for your current and past setups? I'm sure the old ones are in the commit history so could you point me too the place where the colors are stored? Thanks Nerdy :D

**Comment by iyzg** [comment]
i'm so stupid, somehow missed your .xresources lol. I'll be on my way, thanks for great setups Nerdy :heart_eyes:

**Comment by iyzg** [comment]
I take that back once again , can't find any .Xresource colors from a year ago that match up to your Succulent post whelp

**Comment by oppiliappan** [comment]
these are the colours corresponding to that post.
```
#define base00 #212121
#define base01 #303030
#define base02 #353535
#define base03 #4A4A4A
#define base04 #B2CCD6
#define base05 #EEFFFF
#define base06 #EEFFFF
#define base07 #FFFFFF
#define base08 #F07178
#define base09 #F78C6C
#define base0A #FFCB6B
#define base0B #C3E88D
#define base0C #89DDFF
#define base0D #82AAFF
#define base0E #C792EA
#define base0F #FF5370
```

you have to look through commit history to find the other colours haha, i usually mark those commits as "colours" or something similar. i will probably maintain them in separate files henceforth.

**Comment by iyzg** [comment]
oh my bad, thanks man :D
